### ISSUE TITLE
Invoices page break

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#104]
Hi,
There remains one modification on the invoice :
#93 : Do not cut contract invoice on the middle of a contract.

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, 
I've taken a look at this and it looks like it works as expected. 
File is linked below:
https://api.bulbthings.com/files/9c575948-4c75-4138-af21-26cfee2832fd/download?apiToken=08cdee92081e46f2b9ec9abf4b80a7e1-ce4bbf2c2f31b6d7a5738a89a91f6a32

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 

- [ ] We have to keep black line between contract like that
![Line](https://user-images.githubusercontent.com/87650448/132528658-35dbde38-3e2b-4a97-af76-aee81a226d07.png)

- [ ] If we have too many contract for one customer, we have 2 pages :  but on the second page, currently, we havn't any header.
Could you please add same header (logotype + background color + invoice number) and add margin please ?

![page2](https://user-images.githubusercontent.com/87650448/132528872-089b5c99-62c8-486c-a179-c5cb60bc56c2.png)

**Comment by matthewjameslockwood** [comment]
@RomaneJAUD I'm looking into a fix for this now.

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, I've got a change that will show documents to look like the following:
https://api.bulbthings.com/files/42937445-83f4-4e2e-9cd1-3faaf8c6e3fa/download?apiToken=08cdee92081e46f2b9ec9abf4b80a7e1-ce4bbf2c2f31b6d7a5738a89a91f6a32

**Comment by RomaneJAUD** [comment]
Hi,

- [ ] We have to display all informations about one contract on a same page. For example we have to moove on the second page :
```
2021051029_2 - Lamborghini Sián FKP 37
From 01/10/2021 to 31/10/2021
```
![cut](https://user-images.githubusercontent.com/87650448/132710154-d8d51aee-cb45-4d05-a638-f7555e2976a5.png)

- [ ] Could you please add margin before `DESCRIPTION AMOUNT TYPE VAT GROSS AMOUNT`
![marge](https://user-images.githubusercontent.com/87650448/132710602-e3520fc6-f47d-45ba-9210-b6cd9b7d52e2.png)

- [ ] Could you please add space between `"fois"` and `"le"` : ```
Toute somme non payée à l'échéance
donnera lieu à des pénalités fixées à trois **fois le** taux d'intérêt légal, ainsi qu'à la réclamation d'une indemnité forfaitaire de 40 euros pour frais de recouvrement.
``

- [ ] On french doc could you please change wording to display `"Prélèvement le JJ/MM/AAAA"` instead of `"Prélèvement JJ/MM/AAAA"`

Thanks

**Comment by matthewjameslockwood** [comment]
Sorry @RomaneJAUD , this was the file I was meant to link:
https://api.bulbthings.com/files/1cfe71a5-8674-4780-99b9-520a3e0cb200/download?apiToken=08cdee92081e46f2b9ec9abf4b80a7e1-ce4bbf2c2f31b6d7a5738a89a91f6a32

**Comment by RomaneJAUD** [comment]
Yes exactly for first topic, thanks ! 

Still needs doing 3 topics : 

- [ ] Could you please add margin before `DESCRIPTION AMOUNT TYPE VAT GROSS AMOUNT`
![marge](https://user-images.githubusercontent.com/87650448/132710602-e3520fc6-f47d-45ba-9210-b6cd9b7d52e2.png)

- [ ] Could you please add space between `"fois"` and `"le"` : ```
Toute somme non payée à l'échéance
donnera lieu à des pénalités fixées à trois **fois le** taux d'intérêt légal, ainsi qu'à la réclamation d'une indemnité forfaitaire de 40 euros pour frais de recouvrement.
``

- [ ] On french doc could you please change wording to display `"Prélèvement le JJ/MM/AAAA"` instead of `"Prélèvement JJ/MM/AAAA"`

**Comment by matthewjameslockwood** [comment]
Here's the document with the above three changes 😄 :
https://api.bulbthings.com/files/dcc02718-aebf-4da9-886b-7388be49c7e6/download?apiToken=08cdee92081e46f2b9ec9abf4b80a7e1-ce4bbf2c2f31b6d7a5738a89a91f6a32

**Comment by RomaneJAUD** [comment]
Perfect !
So sorry but just could you please : 

- [ ] add pagination please (if many page)
![FACTURE7](https://user-images.githubusercontent.com/87650448/132714281-5ac3c688-e344-47db-8fb6-ccc3adbfe69a.png)

- [ ] add` "Contrat"` before `NTEXXX` for each contratcs : ![FACTURE3](https://user-images.githubusercontent.com/87650448/132714298-280bd8ed-f6e8-4272-89fc-24c6080b917e.png)

- [ ] hide Loc'oto adress please
![FACTURE](https://user-images.githubusercontent.com/87650448/132714720-18e0af87-7c52-4bdb-90c7-0fce9b6adae5.png)

TIA

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, I'm worried that we're making changes by removing things we were asked to add previous..
I was asked to add the Loc'oto address here https://github.com/Bulbthings/bulbthings-locoto/issues/80#issuecomment-909363385, but the above request states you want to remove it.

Some of the images above also don't exactly align with what you're saying in the messages, Should I remove "De" in the 2nd image? Should I remove the "Contrat : NTE1075" also? I'm not sure what the comment about the top right of the document is. 😄

**Comment by RomaneJAUD** [comment]
- [ ] add pagination please (if many page)
![FACTURE7](https://user-images.githubusercontent.com/87650448/132714281-5ac3c688-e344-47db-8fb6-ccc3adbfe69a.png)

- [ ] Don't remove "De" in the 2nd image, just change wording for "Du" : 
Change `De 01/10/2021 au 31/10/2021` for `Du 01/10/2021 au 31/10/2021`

- [ ] add wording` "Contrat"` before `NTEXXX` for each contratcs : ![FACTURE3](https://user-images.githubusercontent.com/87650448/132714298-280bd8ed-f6e8-4272-89fc-24c6080b917e.png)

- [ ] Yes for [#80 (comment)](https://github.com/Bulbthings/bulbthings-locoto/issues/80#issuecomment-909363385) i'm sorry  our team change their mind, could you please hide Loc'oto adress please
![FACTURE](https://user-images.githubusercontent.com/87650448/132714720-18e0af87-7c52-4bdb-90c7-0fce9b6adae5.png)

**Comment by matthewjameslockwood** [comment]
Okay, I can only put the page numbers in the header unfortunately, so i've place it just underneath the document title on the top right.

**Comment by RomaneJAUD** [comment]
Ok thanks, and could you check if invoice reference is `**YYYYMM**_XXXXXX` instead of `YYYYMMDD` please ?

**Comment by matthewjameslockwood** [comment]
Okay, all invoices will then be changed to use that format then

**Comment by RomaneJAUD** [comment]
Perfect, thank you !
