### ISSUE TITLE
Start date (contract) & delivery date (cars)

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#105]
Hi,

`Start date` of the contract must always be equal to `Delivery date` field (cars)

Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD ,

I'm assuming as soon as the `Delivery date` field changes, then we should update the `Start date` of the contract. What happens if this date is different to the contract + all the contract start date? I'm assuming that that's alright.

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 
`Delivery date` is always = `Start date `, if one of these fields is changed we should update other.
I'm not sure if I understand : i_f this date is different to the contract + all the contract start date_ ?
