### ISSUE TITLE
Customers delivery

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#108]
Hi, 
Could you please :

- [x]  Display adress like that : 
`rue`
line break
`zipcode + city`

Example : 
```
VM DISTRIBUTION
Route de la Roche sur Yon 
85260 L'HERBERGEMENT

```
![adress](https://user-images.githubusercontent.com/87650448/132701000-3b45f3b2-92dc-45bc-af57-e8326a73d44c.png)

- [x] Header : change wodring `"PV livraison client"` for >>> `"PV livraison"`
![pv](https://user-images.githubusercontent.com/87650448/132700906-e9ea630b-653d-4570-b8b1-8c5db71430b4.png)

- [x] Change `"Document"` for `"Documents"`
![s](https://user-images.githubusercontent.com/87650448/132701121-0b12b08f-8bff-4e6a-9646-93fc69ee8cb5.png)

- [x] Hide `"Financier" `on this docs (only for "PV livraison" PDF). We have to hide this service (special case for this doc)
![fi](https://user-images.githubusercontent.com/87650448/132701197-7f203afd-6c13-4b9d-99db-173b3653c715.png)

- [x]  Add more padding top and bottom _`"Livreur ou concession"`_ and _`"Date et heure de livraison du véhicule"`_
![space](https://user-images.githubusercontent.com/87650448/132702077-6f85983e-c1ad-42e0-9679-2cfdf954cd44.png)

- [x]  Add more padding top and bottom `"Nom de l'entreprise"`
![space2](https://user-images.githubusercontent.com/87650448/132702163-4658f3df-91a4-4ecf-95b8-682a0146bbfb.png)

- [x]  Reduce width` "Commentaire"` but add more padding bottom, right and left for` "Signature"` 
![com](https://user-images.githubusercontent.com/87650448/132702393-d503253f-0683-4ee8-a29a-f3cd56690e4b.png)

If we can fix these points there will be no further modifications on this doc.
Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, is the following document sufficient for your above mentioned fixes:
https://api.bulbthings.com/files/36ca352f-c859-4c30-bf8a-31090614a009/download?apiToken=08cdee92081e46f2b9ec9abf4b80a7e1-ce4bbf2c2f31b6d7a5738a89a91f6a32

**Comment by matthewjameslockwood** [comment]
The address issue looks like it's a data problem, that's why it's repeated across a lot of different clients at the moment.
I have a fix for that.

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 

Thanks for fix, 

- [ ] Could you please reduce a little bit `Commentaires` block width and extend a little bit `Signature` block width. Like that please :  
![sign](https://user-images.githubusercontent.com/87650448/132860229-2c2f3f33-3ff8-414b-aab5-d87b24454ec2.png)

- [ ] We haven't to display "undefined" if is an empty field. For example : `Couleur extérieur `

- [ ] Yes address issue lit's a data problem, but we have a page layout issue too. We still have customer adress display on 1 line, we would like display customer adress excactly like that please (currently missing line break between street and zip code+city) : 

`rue`
line break
`zipcode + city`

Example, currently we have : 
`8-10 rue Barbette 75003 PARIS`

but we would like
`8-10 rue Barbette `
`75003 PARIS`

Thanks

**Comment by matthewjameslockwood** [comment]
Hi Romane, we will need to resync company information with hubspot after my PR gets merged. I will keep an eye on this issue.
