### ISSUE TITLE
Purchase Order - Bon de commande

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#109]
Hi,
[Example](https://api.bulbthings.com/files/3e23b658-9c97-4c73-8eac-523b2dc8b13c/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-fd91fa4f0eb2f458a88979f99b3e96ae)

- [x] It's commercial car but we have `Total TTC remisé.`
If it's VU we have to display `"HT"` for `Total HT remisé.` `Montant HT.`
If it's VP we have to display `"TTC"` for `Total TTC remisé.` `Montant TTC.`
![TTC](https://user-images.githubusercontent.com/87650448/132703221-d341b432-34cf-4e46-bf9b-67bd192a9f12.png)

- [x] "Nombre de portes" is always empty, could you please request number of doors in JATO and display this information ?

If we can fix these points there will be no further modifications on this doc.
Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, for you second point,  could I please get an example of a vehicle you use where the number of doors doesn't pull through correctly?
I used the following set up and the doors did seem to work:
![image](https://user-images.githubusercontent.com/69078864/132866477-e4d812b3-d7c5-4dcc-9da1-13562f922d26.png)

So there is probably an issue with some other vehicles.

**Comment by RomaneJAUD** [comment]
Hi, @matthewjameslockwood 
I can't find any more example, so ok for this point
