### ISSUE TITLE
Customers confirmation 

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#110]
Hi,

Could you please : 

- [ ]  Display adress like that : 
`rue`
line break
`zipcode + city`

Example : 
```
VM DISTRIBUTION
Route de la Roche sur Yon 
85260 L'HERBERGEMENT

```
![adress2](https://user-images.githubusercontent.com/87650448/132704801-cb8b6ebf-cec6-49d0-87b1-0b2c8ce3cb9b.png)

- [x] Hide `"Financier" `on this docs (only for "PV livraison" PDF). We have to hide this service (special case for this doc)
![fin](https://user-images.githubusercontent.com/87650448/132704982-db882623-a3db-4779-92cc-8ff2dfc05137.png)

- [x] Extend margin top and bottom for `"Délais théorique de livraison ..." `block and between `"Délais théorique de livraison ..." ` and `"Lieu de Livraison`" (line height)
![liv](https://user-images.githubusercontent.com/87650448/132705130-0f8ce27e-666b-4c15-bcd4-0a6998ff52da.png)

- [x] Could you please write in bold character `"Délais théorique de livraison ..." ` and `"Lieu de Livraison`" 
![liv](https://user-images.githubusercontent.com/87650448/132705130-0f8ce27e-666b-4c15-bcd4-0a6998ff52da.png)

- [x] "Nombre de portes" is always empty, could you please request number of doors in JATO and display this information ?

If we can fix these points there will be no further modifications on this doc.
Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, could you please give an example of car number of doors, this issue was mentioned in this issue https://github.com/Bulbthings/bulbthings-locoto/issues/109. The other points have been done in the meantime
