### ISSUE TITLE
Cotation - Carburant cost

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#111]
Hi,
Could you please add this cost to `Total TTC remisé` :  `Total TTC remisé` = `(TOTAL - REMISE)` +`Carburant`
[Doc - 2021-09-09T180951.068.pdf](https://github.com/Bulbthings/bulbthings-locoto/files/7138125/Doc.-.2021-09-09T180951.068.pdf)

We must not apply reduction on `Frais de carburant`

Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, I'm going to assume in the title you meant 'Purchase order'.
