### ISSUE TITLE
Split services into subservices in the invoices pdf

### ISSUE THREAD

**Issue by matthewjameslockwood** [Bulbthings/bulbthings-locoto#23]
Some financial services within contracts have sub-services within them and need to be flattened so they're displayed correctly inside an invoice. They should be flattened for both `Medium-term contract` and `Contract hire` contract types

**Comment by RomaneJAUD** [comment]
Hi,

Actually,  "Financier" corresponds only to the management rent (Loyer de gestion). "Loyer financier" isn't add into "Financier".

![loyer](https://user-images.githubusercontent.com/87650448/127626909-99f6ee8b-8ed9-473a-87c3-45e6480999c2.png)
