### ISSUE TITLE
Import data into system

### ISSUE THREAD

**Issue by matthewjameslockwood** [Bulbthings/bulbthings-locoto#24]
We have to import Loc'oto data into the system. I haven't taken a look at the data just yet, but have created this ticket to keep track of what needs to be done.

**The below is a copy paste from an email**

We have prepared the [import file in the tab "072021_TEST VHA / LLD"](https://t.sidekickopen45.com/s3t/c/5/f18dQhb0S7kv8bp__RW5RlZd42zGCwVW8Jbw_81q7jvFVf6rd23LP-NCW5wvCHT16gGzXf4dVwCV01?te=W3R5hFj4cm2zwW3H8_MV1Jz9RGW3P3n_M3Fbt5SW4cNF573z8Qr2W3K3q0m1LwngpW38349w41slzdW2t2w114r8fMnW2zNM192PS53yW22Vxy21SwhwdW3SDgHt1NjTCtW3VyjDX3K2-zCW1hT8M-2dLQWCF1X0-zGpjJW1&si=4922054762299392&pi=b76419fb-489c-420d-bbf0-7bb8ed4bd98c)
Would I let you check the columns for the IDs, so I can complete them?
We have added several columns concerning missing services in the original file:

Replacement vehicle services:

associations.7.id
associations.7.associationTypeId
associations.7.sourceEntity.id
associations.7.sourceEntity.entityTypeId associations.7.sourceEntity.attributes.serviceCategory associations.7.sourceEntity.attributes.totalVatRate.% associations.7.sourceEntity.attributes.totalGrossAmount.EUR associations.7.sourceEntity.attributes.numberOfT

Insurance benefit :

associations.8.id associations.8.associationTypeId associations.8.sourceEntity.id associations.8.sourceEntity.entityTypeId associations.8.sourceEntity.attributes.serviceCategory associations.8.sourceEntity.attributes.totalVatRate.% associations.8.sourceEntity. attributes.totalGrossAmount.EUR associations.8.sourceEntity.attributes.numberOfTyres

We have highlighted row 9. Alert point: this is a contract modification.

During the previous import, the services were created in duplicate (auto generation of services + creation of the same service with the amounts indicated in the import).
Do not hesitate to come back to us if there are any blocking points or other.
Looking forward to your return.

**Comment by RomaneJAUD** [comment]
Hello,

If I might, can we make sure not to overwrite the quotes made?
We would like the import only impact contracts and not quotes

TIA
