### ISSUE TITLE
PurchaseOrder - Document modifications #2

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#33]
Hi,
Thanks #26  ! We still have 3 small corrections please (for example ) :

"Département de coeur en undefined" : If "Département de coeur" is empty we have too hide this text

Transalte : Transmission Manual for Transmission : Manuel.

"Règlement à 30 jours à la date de livraison. La facture devra être libellée à l’ordre de : BOUGUENAIS" could you please remplace for :
Règlement à 30 jours à la date de livraison. (break line)
La facture devra être libellée à l’ordre de : Loc’oto, 1 rue Clément Ader 44340 BOUGUENAIS

- "Puissance fiscale" is not displayed while she's present in actif detail.

- Add "N° de contrat" on PDF

- Add insert for car dealer signature
![Screenshot](https://user-images.githubusercontent.com/87650448/127633088-01126065-6d8a-48ab-8a62-d39a0a21b6b5.png)

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, 

I'm busy with this issue at the moment, I'm a little confused with the last three points:
- "Puissance fiscale" is not displayed while she's present in actif detail.
This should be indicated as "Puissance F." in the first table. Do you have a link/picture of the document you generated?
- Add "N° de contrat" on PDF
The contract number is currently shown in the header of the first table. I'm going to add the contract number to the filename also. I'm unsure if you want it in a place that's a little clearer.
- Add insert for car dealer signature
Do you think that this should rather be below the last table, like so?
![image](https://user-images.githubusercontent.com/69078864/128006718-a5b3b528-d76b-4ee2-8068-65e124f4e853.png)

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 
I'm sorry, I was on vacation for 2 weeks.

- Yes Puissance Fiscale should be indicated as "Puissance F." but this field is always empty. For example : 2021081115 while this information isn't empty on asset information.
![puissance](https://user-images.githubusercontent.com/87650448/129539190-ae32f400-a7b7-47df-9d9a-89b272b67a10.png)

- Contract number isn't display. For example VHA1045 is empty
![contrat](https://user-images.githubusercontent.com/87650448/129538564-038b9926-5269-4f6a-8a90-1bc26176efab.PNG)

- With insert for car dealer signature below the last table it's perfect.

Thanks

**Comment by matthewjameslockwood** [comment]
I have done the above fixes and should see them live soon :)
