### ISSUE TITLE
Contract attributes - Step "Devis validé"

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#36]
Hi,

When contract's statues are "Devis validé", it should no longer be able to modify the attributes : 

- Reférence
- Periodicity
- Contract start date
- Mileage
- Periodic payment
- Initial mileage
- Payment type
- Quotation date
- All services costs

Thx

**Comment by matthewjameslockwood** [comment]
A system update will need to be done before this issue can be completed @flmg.

**Comment by RomaneJAUD** [comment]
As mentioned together with Yann, if isn't possible : block all field "Contract" for all quotation whose statut = Devis validé 

TIA
