### ISSUE TITLE
Report services - Analyse

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#37]
Hi,

Could you allow us to create reports (tab or other) on services and sub-services ?
For example : sum of "Loyer de gestion" for all the contracts of the same client.
Goal : Quick view of the full cost of services X for a client Y

Thx

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, this should already be possible. We can take a look at it when you get back.
