### ISSUE TITLE
Purchase Order - Type VU

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#42]
If car is VU, orders display the amounts excluding tax. Could you please :

- Display wording "HT" instead of TTC
![wording](https://user-images.githubusercontent.com/87650448/127633796-6d5ad0d7-c99a-4911-9032-c49b5e9ef4c5.PNG)

- The price of the options is displayed in TTC instead of HT. 
![ht](https://user-images.githubusercontent.com/87650448/127633870-f4ddc2f9-95de-4590-ab22-c929d55bbb79.PNG)

Thx

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, if the price of vehicle options should be displayed in HT, should the price of vehicle services also be displayed in HT?

**Comment by yanndepond** [comment]
Hi @matthewjameslockwood, HT is for "VU" (CV) and TTC for "VP" (PV)

**Comment by RomaneJAUD** [comment]
Hi, 
@matthewjameslockwood we still have "TOTAL TTC REMISÉ" for VU : https://api.bulbthings.com/files/acf10923-fdaa-48e6-a12b-b80c9420a510/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-ca00d0a1b324732250851839da4f180d

We would like "TOTAL HT REMISÉ" please
