### ISSUE TITLE
Contractual end date

### ISSUE THREAD

**Issue by matthewjameslockwood** [Bulbthings/bulbthings-locoto#44]
At the moment, the contract end date is calculated by adding a certain number of months to a start date, eg, if a contract starts on the 1st february 2021 and has a three month duration, the contract end date will be 1st May 2021. Is this the correct calculation for the end date of a contract? Should it rather be the the end of April, so the 30th of April?

@RomaneJAUD, just mentioning you in this issue.

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 
For LMD : if a contracts on the 1st february 2021 and has a three month duration, the contract end date will be 1st May 2021.
For LLD : if a contracts on the 1st february 2021 and the contract end date will be 1st May 2022. At the end of the term we invoice contract and we generate a credit note for the number of days after return of the vehicle.

**Comment by matthewjameslockwood** [comment]
Okay, 
For LMD: will the last day of the contract be charged? As in, will the 1st of May be charged as a single day?
For LLD:  again, will the last day be charged?

**Comment by RomaneJAUD** [comment]
Yes if contract is three month duration, we charge all day during three month.

For LMD:  the 1st of May be charged as a single day  (at the end of the term)
For LLD: we charge all period (fall due) and then we generate a credit note for the number of days after return of the vehicle (for example if a contracts on the 1st february 2021 and the contract end date (return date) will be 1st May 2022, we charge everydays and we generate a credit note for 2022-05-02 to 2022-05-31.

**Comment by matthewjameslockwood** [comment]
Okay thanks @RomaneJAUD.
I'm just checking because this also means that there will be extra days on the payment schedule document that will be generated. 

I want to just try an example with an LMD contract, if a three month LMD contract with the payment type 'arrears' is chosen, the following payment lines will be shown:
01/02/2021 - 28/02/2021  - x cost
01/03/2021 - 31/03/2021   - x cost
01/04/2021 - 30/04/2021 - x cost
01/05/2021 - 01/05/2021 - x/30 cost
Would that be correct?

**Comment by RomaneJAUD** [comment]
Yes,
01/02/2021 - 28/02/2021 - x cost
01/03/2021 - 31/03/2021 - x cost
01/04/2021 - 30/04/2021 - x cost
01/05/2021 - 01/05/2021 - x/30 cost 

Every month=30day. Every day is charge.

For example february : 
Contract strat date :15-02-2021 
Duration = 1 mois 
Contract end date: 15-03-2021

We generate 2 invoices : 
1. First invoice 28-02-2021 > 30 days charge
2. New invoice for 01-03-2021 to 15-03-2021 = (periodic payment/30)*15

**Comment by matthewjameslockwood** [comment]
Okay cool, thanks
