### ISSUE TITLE
Entretien - Total Net Amount for "VP ou VU" = VU

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#48]
Hi,

If we make a VU quotation, "Entretien" Total Gross Amount is calculated with Catalogue Purchase Price without VAT. 
Could you change for get Total Net Amount instead of Total Gross Amount ?
Than VAT is applied

For VPs, calculation doen't change.
![tva](https://user-images.githubusercontent.com/87650448/129594211-4290a62e-5ce7-4109-b062-924dcd079d6f.png)

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD,

If this service is for a vehicle that is 'VP', should the tax rate rather be 0%? As no tax will be applied to the service?

**Comment by RomaneJAUD** [comment]
@matthewjameslockwood 20% VAT must be kept for VP and VU

**Comment by matthewjameslockwood** [comment]
Thanks @RomaneJAUD, I have cleared this up with @yanndepond 😄

**Comment by RomaneJAUD** [comment]
Ok perfect 👍

**Comment by matthewjameslockwood** [comment]
This might open up a larger problem, but should the `Prix total du véhicule` field also include/exclude tax depending on whether the vehicle is VP or VU?

**Comment by RomaneJAUD** [comment]
"Prix total du véhicule" already changes according to the type VP or VU

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood, is it clear to you? :)
