### ISSUE TITLE
Purchase Order - Car dealer informations + clients informations

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#58]
Hi,

On Purchase Order we don't understand "Informations clients : :" part. For exemple :

- This [Purchase Order](https://api.bulbthings.com/files/b99ad703-7c27-47f4-bf44-979d1a7901d3/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-ca00d0a1b324732250851839da4f180d) : there is I_nformations clients : ATX 2 :_ while campagny isn't link with this contract.

- Also, on [this Purchase Order](https://api.bulbthings.com/files/70e3806e-dc11-49e0-82c6-76f2a7ce8582/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-ca00d0a1b324732250851839da4f180d), _Informations clients : :_ is empty while a compagny is link with this contract.

Could you check please and explain us why ?

Also informations of the supplier (car dealer)  isnt indicated. 
We would like like this : https://docs.google.com/document/d/1RCv9nm7rGOjv_DpK5FIekF_ql1DRVhi9/edit
Nom de la concession
Adresse de la concession
CP et ville de la concession
à l’attention de [contact name]

TIA

**Comment by matthewjameslockwood** [comment]
Both the contract and the vehicle need to be attached to the company. For contract `2021081113`, the vehicle is attached to the correct company while the contract is not. For the contract `2021081119`, the contract is attached to the correct company, but the vehicle is not.

**Comment by matthewjameslockwood** [comment]
Also, the vehicle should be linked to the car dealer also in order to see the address information of the car dealer 😄

**Comment by RomaneJAUD** [comment]
Ok thanks 👍 but only company adress is display (name missing). Could you display also company name please ?
For example : https://api.bulbthings.com/files/817cb8bd-7bf5-4d80-a6d6-b554244f89aa/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-ca00d0a1b324732250851839da4f180d

**Comment by matthewjameslockwood** [comment]
I've added a change that shows the car dealer company name :)
