### ISSUE TITLE
PDF invoice - Modification #3

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#80]
Hi,
Could you apply modifications please ?

1. ![facture](https://user-images.githubusercontent.com/87650448/131004869-39c08590-3600-4f22-9020-1f5ec985bbe5.png)

2. Today it's display like #38  : 
NTE1041
PEUGEOT 308
FZ797-QM : ANTHONY MANDIN

Could you please display like this please :
NTE1041 - PEUGEOT 308
FZ797-QM : ANTHONY MANDIN

3. Financier = Loyer financier + loyer de gestion so this display is a duplication :
![loyer](https://user-images.githubusercontent.com/87650448/131005640-c63c092d-f040-4aa3-aa18-0f9153f39b82.png)
Could you please do not display "Financier" ? (Financier must be only display on cotation)

If necessary you can check template : https://docs.google.com/document/d/1xVPpjL3-zfNEuWhPEIPyKfSfSkAMRSNz8Rf1wtrZl7M/edit

Thanks

**Comment by matthewjameslockwood** [comment]
I've pushed a fix in the above PR to hide the line "Financier".

**Comment by RomaneJAUD** [comment]
Thanks @matthewjameslockwood 

I just tested for a real contract and customer. [Example](https://api.bulbthings.com/files/23720246-d1d9-48ac-a9f9-cf4f925233d3/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-f0b26c5cfe46f3262249b3e1d50982d9).
But it's not in production for the moment ?

**Comment by matthewjameslockwood** [comment]
It is not just yet @RomaneJAUD, I will tell you when it's in production 😄

**Comment by RomaneJAUD** [comment]
Ok thanks ! 
Could you please add our adress :
![Screenshot](https://user-images.githubusercontent.com/87650448/131535445-e1a25ccd-6c39-4ef8-8a68-aa61234a76e7.png)
 
Loc’oto
1 rue Clément Ader
44340 Bouguenais
