### ISSUE TITLE
Bon de commande - Modifications 

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#84]
Hi,

- [ ] @matthewjameslockwood this issue (#74) is closed but we doesn't have by default : _Ville d'achat = Loc'oto, 1 rue Clément Ader, 44340 BOUGUENAIS_ Could you add this adress please ?

- [ ] #85
[For example](https://api.bulbthings.com/files/26d41878-b4db-4b26-bf6e-c12ff0aa9923/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-f452701cfa5a0fd76f2258bbe74bd59f)

TIA

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD , I've re-opened the first issue in the previous ticket. I will keep track of it there.

For the second point, I've created a separate issue. We can track both issues in those issues, I will close this ticket.
