### ISSUE TITLE
Biling cycle - Empty invoice

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#96]
Hi,
On "Locoto TEST", we launch billing cycle LLD (21_08_25). For IKKS PRESTATIONS we have a "A la route" contract, but invoice is empty. Why ?
![Factures](https://user-images.githubusercontent.com/87650448/132229683-c67145a1-d64c-4997-a088-660e2df24bb9.png)

Thanks

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, if you take a look at the error document that is generated it looks like there are a few issues with that customer.

**Comment by RomaneJAUD** [comment]
Ok thanks @matthewjameslockwood 
Is it possible to not generate invoices if they have errors (rather than an empty invoice) please ?

Thanks

**Comment by RomaneJAUD** [comment]
@matthewjameslockwood we still have empty invoice for IKKS PRESTATION (NTE1075) but any information about that on error report : https://api.bulbthings.com/files/8219e401-2e1d-4e95-9799-9f2572fb59c1/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-3f0f5a804c678750e48137e3ce76c684

But when we check document, we have an invoice 
![facturesikks](https://user-images.githubusercontent.com/87650448/132240028-7218160a-0e12-4fa4-b8a9-cbb235eb03e0.png)

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, I'm just testing this on my local system, looks like that invoice was generated from that.
I'm not sure why there are a bunch of blank invoices generated on that customer, could they have been created manually by someone?
I'm taking a look at this now

**Comment by matthewjameslockwood** [comment]
I've found the issue @RomaneJAUD. The fix for it is above.
